yolo

diff --git a/.github/workflows/cmake_ctest.yml b/.github/workflows/cmake_ctest.yml
--- a/.github/workflows/cmake_ctest.yml
+++ b/.github/workflows/cmake_ctest.yml
@@ -47,12 +47,17 @@ jobs:
       with:
         submodules: true # Get JUCE populated
 
+#  set(COMPANY_NAME "Pimplejuce inc")
+#  set(BUNDLE_ID "com.pimplejuce.pimp")
+
     - name: Extract CMake Variables
       shell: bash
       run: |
         project_name=$(grep -oP '^set\(PROJECT_NAME "\K[^"]+' CMakeLists.txt || echo "")
         project_version=$(grep -oP '^set\(PROJECT_VERSION "\K[^"]+' CMakeLists.txt || echo "")
         product_name=$(grep -oP '^set\(PRODUCT_NAME "\K[^"]+' CMakeLists.txt || echo "")
+        company_name=$(grep -oP '^set\(COMPANY_NAME "\K[^"]+' CMakeLists.txt || echo "")
+        bundle_id=$(grep -oP '^set\(BUNDLE_ID "\K[^"]+' CMakeLists.txt || echo "")
 
         if [ -z "$project_name" ]; then
           echo "PROJECT_NAME not found"
@@ -71,10 +76,34 @@ jobs:
         else
           echo "PRODUCT_NAME=${product_name}" >> $GITHUB_ENV
         fi
-    
+        
+        if [ -z "$company_name" ]; then
+          echo "COMPANY_NAME not found"
+        else
+          echo "COMPANY_NAME=${company_name}" >> $GITHUB_ENV
+        fi
+        
+        if [ -z "$bundle_id" ]; then
+          echo "BUNDLE_ID not found"
+        else
+          echo "BUNDLE_ID=${bundle_id}" >> $GITHUB_ENV
+        fi
+
+    - name: Setup Environment Variables
+      shell: bash
+      run: |
+        VERSION=$(cat VERSION)
+        echo "ARTIFACTS_PATH=${{ env.BUILD_DIR }}/${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}" >> $GITHUB_ENV
+        echo "VST3_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/VST3/${{ env.MY_PRODUCT_NAME }}.vst3" >> $GITHUB_ENV
+        echo "AU_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AU/${{ env.MY_PRODUCT_NAME }}.component" >> $GITHUB_ENV
+        echo "AUV3_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AUv3/${{ env.MY_PRODUCT_NAME }}.appex" >> $GITHUB_ENV
+#        echo "PRODUCT_NAME=${{ env.PROJECT_NAME }}-$VERSION-${{ matrix.name }}" >> $GITHUB_ENV
 
     - name: Stop workflow
-      run: echo "::error::Exiting workflow"
+      shell: bash
+      run: |
+        echo "::error::Exiting workflow"
+        exit 1
 
     # This is just easier than debugging different compilers on different platforms
     - name: Set up Clang
@@ -124,15 +153,6 @@ jobs:
       run: brew install ninja osxutils
 
 
-    - name: Setup Environment Variables
-      shell: bash
-      run: |
-        VERSION=$(cat VERSION)
-        echo "ARTIFACTS_PATH=${{ env.BUILD_DIR }}/${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}" >> $GITHUB_ENV
-        echo "VST3_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/VST3/${{ env.PROJECT_NAME }}.vst3" >> $GITHUB_ENV
-        echo "AU_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AU/${{ env.PROJECT_NAME }}.component" >> $GITHUB_ENV
-        echo "AUV3_PATH=${{ env.PROJECT_NAME }}_artefacts/${{ env.BUILD_TYPE }}/AUv3/${{ env.PROJECT_NAME }}.appex" >> $GITHUB_ENV
-        echo "PRODUCT_NAME=${{ env.PROJECT_NAME }}-$VERSION-${{ matrix.name }}" >> $GITHUB_ENV
 
     - name: ccache
       uses: hendrikmuhs/ccache-action@main
